export const tools = [
  // Calculators
  {
    slug: "iv-drip-rate-calculator",
    icon: "🗓️",
    title: "IV Drip Rate Calculator",
    subtitle: "Cross-check drops/min and mL/hr",
    category: "Calculators",
    iconTone: "blue" as const,
  },
  {
    slug: "liquid-dose-calculator",
    icon: "🧴",
    title: "Liquid Dose Calculator",
    subtitle: "Cross-check estimated mL to administer",
    category: "Calculators",
    iconTone: "green" as const,
  },
  {
  slug: "medication-unit-converter",
  icon: "⚖️",
  title: "Medication Unit Converter",
  subtitle: "Cross-check g, mg and micrograms",
  category: "Calculators",
  iconTone: "cyan" as const,
},
  {
    slug: "news2-score",
    icon: "📋",
    title: "NEWS2 Score",
    subtitle: "Reference early warning score",
    category: "Calculators",
    iconTone: "teal" as const,
  },
  {
    slug: "tablet-capsule-calculator",
    icon: "💊",
    title: "Tablet & Capsule Calculator",
    subtitle: "Cross-check tablets or capsules",
    category: "Calculators",
    iconTone: "green" as const,
  },

  // Ranges
  {
    slug: "blood-sugar-testing",
    icon: "🩸",
    title: "Blood Sugar Testing",
    subtitle: "Ranges and testing guide",
    category: "Ranges",
    iconTone: "red" as const,
  },
  {
    slug: "electrolyte-ranges",
    icon: "🧪",
    title: "Electrolyte Ranges",
    subtitle: "Na, K, Ca, Mg levels",
    category: "Ranges",
    iconTone: "lime" as const,
  },
  {
    slug: "normal-vital-signs",
    icon: "🫀",
    title: "Normal Vital Signs",
    subtitle: "Reference ranges",
    category: "Ranges",
    iconTone: "blue" as const,
  },

  // Guides
  {
    slug: "aseptic-non-touch-technique",
    icon: "🧼",
    title: "ANTT",
    subtitle: "Aseptic non-touch technique",
    category: "Guides",
    iconTone: "cyan" as const,
  },
  {
    slug: "cannula-sizes-guide",
    icon: "🏷️",
    title: "Cannula Sizes Guide",
    subtitle: "Colour codes & uses",
    category: "Guides",
    iconTone: "blue" as const,
  },
  {
    slug: "catheter-care",
    icon: "🧷",
    title: "Catheter Care",
    subtitle: "Maintenance & hygiene",
    category: "Guides",
    iconTone: "blue" as const,
  },
  {
    slug: "catheterisation-female",
    icon: "👩",
    title: "Female Catheterisation",
    subtitle: "Procedure overview",
    category: "Guides",
    iconTone: "blue" as const,
  },
  {
    slug: "catheterisation-male",
    icon: "👨",
    title: "Male Catheterisation",
    subtitle: "Procedure overview",
    category: "Guides",
    iconTone: "blue" as const,
  },
  {
    slug: "oxygen-delivery-devices",
    icon: "🫁",
    title: "Oxygen Delivery Devices",
    subtitle: "Flow rates & masks",
    category: "Guides",
    iconTone: "blue" as const,
  },
  {
    slug: "stoma-care",
    icon: "🩹",
    title: "Stoma Care",
    subtitle: "Routine care guide",
    category: "Guides",
    iconTone: "orange" as const,
  },

  // Protocols
  {
    slug: "anaphylaxis-treatment",
    icon: "🚨",
    title: "Anaphylaxis Treatment",
    subtitle: "Emergency response",
    category: "Protocols",
    iconTone: "red" as const,
  },
  {
    slug: "blood-transfusion",
    icon: "🩸",
    title: "Blood Transfusion",
    subtitle: "Checks & monitoring",
    category: "Protocols",
    iconTone: "red" as const,
  },
  {
    slug: "cpr",
    icon: "❤️",
    title: "CPR",
    subtitle: "Basic life support",
    category: "Protocols",
    iconTone: "red" as const,
  },
  {
    slug: "sepsis-6-protocol",
    icon: "⏱️",
    title: "Sepsis 6 Protocol",
    subtitle: "Immediate actions",
    category: "Protocols",
    iconTone: "orange" as const,
  },
];

export type Tool = (typeof tools)[number];